name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Zip
        run: sudo apt-get install -y zip

      - name: Create package
        run: |
          mkdir upload
          cd /launcher/win-x64/ && zip -r ./upload/ClassicUOLauncher-win-x64-release.zip .
          cd ../..
          cd /launcher/linux-x64/ && zip -r ./upload/ClassicUOLauncher-linux-x64-release.zip .
          cd ../..
          cd /launcher/osx-x64/ && zip -r ./upload/ClassicUOLauncher-osx-x64-release.zip .
          cd ../..

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./upload/ClassicUOLauncher-win-x64-release.zip,./upload/ClassicUOLauncher-linux-x64-release.zip,./upload/ClassicUOLauncher-osx-x64-release.zip"
          name: "ClassicUOLauncher Release"
          draft: false
          prerelease: false
          allowUpdates: true
          tag: "launcher-release"
          token: ${{ secrets.GITHUB_TOKEN }}
